version: "3"
services:
  mongodb:
    image: mongo
    container_name: telega-bot-mongo-db
    ports:
      - 8002:27017
    volumes:
      - ../mongoDb:/data/db
      - ../mongoBkp:/data/bkp
    restart: always
  vladimir-bot:
    build: ./
    container_name: telega-bot
    env_file:
      - spring_env.env
    depends_on:
      - mongodb
    ports:
      - "8001:8080"
    links:
      - mongodb
